<a href="https://colab.research.google.com/github/GabrielStamfordDev/Data-Science-First-Steps/blob/main/Alura_03_Pandas_Selecioando_Agrupando_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploades = files.upload()

Saving 1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx to 1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx

In [ ]:
import pandas as pd
df = pd.read_excel('/content/1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx', sheet_name='GEE Estados')
original = df.copy()
df.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,...,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,...,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,...,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,...,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,...,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103312 entries, 0 to 103311
Data columns (total 63 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Nível 1 - Setor             103312 non-null  object
 1   Nível 2                     103312 non-null  object
 2   Nível 3                     103253 non-null  object
 3   Nível 4                     90920 non-null   object
 4   Nível 5                     100788 non-null  object
 5   Nível 6                     97691 non-null   object
 6   Emissão / Remoção / Bunker  103312 non-null  object
 7   Gás                         103312 non-null  object
 8   Estado                      97374 non-null   object
 9   Atividade Econômica         102076 non-null  object
 10  Produto                     37413 non-null   object
 11  1970                        103312 non-null  float64
 12  1971                        103312 non-null  float64
 13  1972                        103312 non-null  float64
 14  1973                        103312 non-null  float64
 15  1974                        103312 non-null  float64
 16  1975                        103312 non-null  float64
 17  1976                        103312 non-null  float64
 18  1977                        103312 non-null  float64
 19  1978                        103312 non-null  float64
 20  1979                        103312 non-null  float64
 21  1980                        103312 non-null  float64
 22  1981                        103312 non-null  float64
 23  1982                        103312 non-null  float64
 24  1983                        103312 non-null  float64
 25  1984                        103312 non-null  float64
 26  1985                        103312 non-null  float64
 27  1986                        103312 non-null  float64
 28  1987                        103312 non-null  float64
 29  1988                        103312 non-null  float64
 30  1989                        103312 non-null  float64
 31  1990                        103312 non-null  float64
 32  1991                        103312 non-null  float64
 33  1992                        103312 non-null  float64
 34  1993                        103312 non-null  float64
 35  1994                        103312 non-null  float64
 36  1995                        103312 non-null  float64
 37  1996                        103312 non-null  float64
 38  1997                        103312 non-null  float64
 39  1998                        103312 non-null  float64
 40  1999                        103312 non-null  float64
 41  2000                        103312 non-null  float64
 42  2001                        103312 non-null  float64
 43  2002                        103312 non-null  float64
 44  2003                        103312 non-null  float64
 45  2004                        103312 non-null  float64
 46  2005                        103312 non-null  float64
 47  2006                        103312 non-null  float64
 48  2007                        103312 non-null  float64
 49  2008                        103312 non-null  float64
 50  2009                        103312 non-null  float64
 51  2010                        103312 non-null  float64
 52  2011                        103312 non-null  float64
 53  2012                        103312 non-null  float64
 54  2013                        103312 non-null  float64
 55  2014                        103312 non-null  float64
 56  2015                        103312 non-null  float64
 57  2016                        103312 non-null  float64
 58  2017                        103312 non-null  float64
 59  2018                        103312 non-null  float64
 60  2019                        103312 non-null  float64
 61  2020                        103312 non-null  float64
 62  2021                        103312 non-null  float64
dtypes: float64(52), object(11)
memory usage: 49.7+ MB

In [ ]:
df['Emissão / Remoção / Bunker'].unique()

array(['Remoção NCI', 'Remoção'], dtype=object)

In [ ]:
df[df["Emissão / Remoção / Bunker"].str.contains('Remoção', na=False)]
# df = df[df["Emissão / Remoção / Bunker"].isin(['Remoção', 'Remoção NCI'])]

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23520,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RO,PEC,...,-1.434540e+07,-1.499358e+07,-1.543196e+07,-1.567070e+07,-1.630063e+07,-1.702215e+07,-1.740074e+07,-1.771914e+07,-1.767632e+07,-1.838895e+07
23521,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AC,PEC,...,-5.382949e+06,-5.524659e+06,-5.632429e+06,-5.765030e+06,-5.867354e+06,-5.942076e+06,-6.022000e+06,-6.002147e+06,-6.035591e+06,-6.459079e+06
23522,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AM,PEC,...,-3.450455e+06,-3.540294e+06,-3.545724e+06,-3.924546e+06,-4.626541e+06,-4.874199e+06,-4.849173e+06,-4.959540e+06,-5.106806e+06,-5.809814e+06
23523,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RR,PEC,...,-1.260166e+06,-1.261895e+06,-1.371664e+06,-1.501452e+06,-1.507705e+06,-1.509919e+06,-1.609826e+06,-1.616980e+06,-1.518397e+06,-1.926000e+06
23524,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),PA,PEC,...,-3.429279e+07,-3.317185e+07,-3.281628e+07,-3.350720e+07,-3.557183e+07,-3.755308e+07,-4.134614e+07,-4.229403e+07,-4.275448e+07,-4.443440e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102751,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR4,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102752,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MT,AGROPEC,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102753,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102754,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MT,AGROPEC,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102755,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05

In [ ]:
df.loc[df['Emissão / Remoção / Bunker'].isin(['Remoção', 'Remoção NCI']), 1970:2021] # Bolean Mask

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.434540e+07,-1.499358e+07,-1.543196e+07,-1.567070e+07,-1.630063e+07,-1.702215e+07,-1.740074e+07,-1.771914e+07,-1.767632e+07,-1.838895e+07
23521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-5.382949e+06,-5.524659e+06,-5.632429e+06,-5.765030e+06,-5.867354e+06,-5.942076e+06,-6.022000e+06,-6.002147e+06,-6.035591e+06,-6.459079e+06
23522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.450455e+06,-3.540294e+06,-3.545724e+06,-3.924546e+06,-4.626541e+06,-4.874199e+06,-4.849173e+06,-4.959540e+06,-5.106806e+06,-5.809814e+06
23523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.260166e+06,-1.261895e+06,-1.371664e+06,-1.501452e+06,-1.507705e+06,-1.509919e+06,-1.609826e+06,-1.616980e+06,-1.518397e+06,-1.926000e+06
23524,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.429279e+07,-3.317185e+07,-3.281628e+07,-3.350720e+07,-3.557183e+07,-3.755308e+07,-4.134614e+07,-4.229403e+07,-4.275448e+07,-4.443440e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102753,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05

In [ ]:
df.loc[df['Emissão / Remoção / Bunker'].isin(['Remoção', 'Remoção NCI']), 1970:2021].max()
# The Results indicates that they are actually of remotion

1970    0.0
1971    0.0
1972    0.0
1973    0.0
1974    0.0
1975    0.0
1976    0.0
1977    0.0
1978    0.0
1979    0.0
1980    0.0
1981    0.0
1982    0.0
1983    0.0
1984    0.0
1985    0.0
1986    0.0
1987    0.0
1988    0.0
1989    0.0
1990    0.0
1991    0.0
1992    0.0
1993    0.0
1994    0.0
1995    0.0
1996    0.0
1997    0.0
1998    0.0
1999    0.0
2000    0.0
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
2021    0.0
dtype: float64

In [ ]:
# df.loc[df['Emissão / Remoção / Bunker'].isin(['Bunker']), :]

Empty DataFrame
Columns: [Nível 1 - Setor, Nível 2, Nível 3, Nível 4, Nível 5, Nível 6, Emissão / Remoção / Bunker, Gás, Estado, Atividade Econômica, Produto, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
Index: []

[0 rows x 63 columns]

In [ ]:
df = df.loc[['Emissão / Remoção / Bunker'] == 'Emissão', :]
df = df.drop(columns='Emissão / Remoção / Bunker')
df

In [ ]:
# Q1:
df['Estado'].unique()

array(['RO', 'AC', 'AM', 'RR', 'PA', 'AP', 'TO', 'MA', 'PI', 'CE', 'RN',
       'PB', 'PE', 'AL', 'SE', 'BA', 'MG', 'ES', 'RJ', 'SP', 'PR', 'SC',
       'RS', 'MS', 'MT', 'GO', 'DF'], dtype=object)

In [ ]:
print(len(df['Estado'].unique()))

27

In [ ]:
df['Nível 1 - Setor'].unique()
# setores = df['Nível 1 - Setor'].unique()
# print(len(setores))
# for setor in setores:
#   print(setor)

array(['Agropecuária', 'Mudança de Uso da Terra e Floresta'], dtype=object)

In [ ]:
#Q2
df.loc[df['Estado'].isin(['PR', 'SC', 'RS']), :]

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23540,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),PR,PEC,...,-5.900507e+06,-5.984675e+06,-6.073376e+06,-6.150885e+06,-6.151068e+06,-6.124263e+06,-5.855391e+06,-5.905203e+06,-5.870802e+06,-5.642886e+06
23541,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),SC,PEC,...,-1.659724e+06,-1.782825e+06,-1.873500e+06,-1.984450e+06,-2.043106e+06,-1.971157e+06,-1.832067e+06,-1.902826e+06,-1.899911e+06,-1.783246e+06
23542,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RS,PEC,...,-5.360004e+05,-5.918754e+05,-6.303546e+05,-6.919717e+05,-7.181036e+05,-6.844659e+05,-5.946423e+05,-6.265604e+05,-6.288892e+05,-6.196878e+05
23567,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2e (t) GWP-AR5,PR,PEC,...,-5.900507e+06,-5.984675e+06,-6.073376e+06,-6.150885e+06,-6.151068e+06,-6.124263e+06,-5.855391e+06,-5.905203e+06,-5.870802e+06,-5.642886e+06
23568,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2e (t) GWP-AR5,SC,PEC,...,-1.659724e+06,-1.782825e+06,-1.873500e+06,-1.984450e+06,-2.043106e+06,-1.971157e+06,-1.832067e+06,-1.902826e+06,-1.899911e+06,-1.783246e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102643,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pampa,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GTP-AR6,RS,AGROPEC,...,-2.602140e+05,-2.558180e+05,-2.613230e+05,-2.729020e+05,-2.796870e+05,-2.835100e+05,-2.871630e+05,-2.876180e+05,-2.886850e+05,-2.645790e+05
102644,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pampa,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR2,RS,AGROPEC,...,-2.602140e+05,-2.558180e+05,-2.613230e+05,-2.729020e+05,-2.796870e+05,-2.835100e+05,-2.871630e+05,-2.876180e+05,-2.886850e+05,-2.645790e+05
102645,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pampa,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR4,RS,AGROPEC,...,-2.602140e+05,-2.558180e+05,-2.613230e+05,-2.729020e+05,-2.796870e+05,-2.835100e+05,-2.871630e+05,-2.876180e+05,-2.886850e+05,-2.645790e+05
102646,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pampa,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,RS,AGROPEC,...,-2.602140e+05,-2.558180e+05,-2.613230e+05,-2.729020e+05,-2.796870e+05,-2.835100e+05,-2.871630e+05,-2.876180e+05,-2.886850e+05,-2.645790e+05
102647,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pampa,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,RS,AGROPEC,...,-2.602140e+05,-2.558180e+05,-2.613230e+05,-2.729020e+05,-2.796870e+05,-2.835100e+05,-2.871630e+05,-2.876180e+05,-2.886850e+05,-2.645790e+05

In [ ]:
#Q3
selec = (df['Nível 1 - Setor'] == 'Mudança de Uso da Terra e Floresta') & (df['Estado'] == 'AM')
df[selec]

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
95774,Mudança de Uso da Terra e Floresta,Remoção em Áreas Protegidas,Amazônia,em Área Protegida,Vegetação nativa estável,Floresta primária -- Floresta primária,Remoção,CO2 (t),AM,NaN,...,-137144736.0,-138051299.0,-140432027.0,-141711670.0,-142988287.0,-147647577.0,-147634381.0,-147927249.0,-147899303.0,-147760711.0
95783,Mudança de Uso da Terra e Floresta,Remoção em Áreas Protegidas,Amazônia,em Área Protegida,Vegetação nativa estável,Floresta primária -- Floresta primária,Remoção,CO2e (t) GTP-AR2,AM,NaN,...,-137144736.0,-138051299.0,-140432027.0,-141711670.0,-142988287.0,-147647577.0,-147634381.0,-147927249.0,-147899303.0,-147760711.0
95792,Mudança de Uso da Terra e Floresta,Remoção em Áreas Protegidas,Amazônia,em Área Protegida,Vegetação nativa estável,Floresta primária -- Floresta primária,Remoção,CO2e (t) GTP-AR4,AM,NaN,...,-137144736.0,-138051299.0,-140432027.0,-141711670.0,-142988287.0,-147647577.0,-147634381.0,-147927249.0,-147899303.0,-147760711.0
95801,Mudança de Uso da Terra e Floresta,Remoção em Áreas Protegidas,Amazônia,em Área Protegida,Vegetação nativa estável,Floresta primária -- Floresta primária,Remoção,CO2e (t) GTP-AR5,AM,NaN,...,-137144736.0,-138051299.0,-140432027.0,-141711670.0,-142988287.0,-147647577.0,-147634381.0,-147927249.0,-147899303.0,-147760711.0
95810,Mudança de Uso da Terra e Floresta,Remoção em Áreas Protegidas,Amazônia,em Área Protegida,Vegetação nativa estável,Floresta primária -- Floresta primária,Remoção,CO2e (t) GTP-AR6,AM,NaN,...,-137144736.0,-138051299.0,-140432027.0,-141711670.0,-142988287.0,-147647577.0,-147634381.0,-147927249.0,-147899303.0,-147760711.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99986,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Amazônia,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GTP-AR6,AM,AGROPEC,...,-220554.0,-232664.0,-250233.0,-252002.0,-256416.0,-261695.0,-262774.0,-266459.0,-283540.0,-279467.0
99995,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Amazônia,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR2,AM,AGROPEC,...,-220554.0,-232664.0,-250233.0,-252002.0,-256416.0,-261695.0,-262774.0,-266459.0,-283540.0,-279467.0
100004,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Amazônia,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR4,AM,AGROPEC,...,-220554.0,-232664.0,-250233.0,-252002.0,-256416.0,-261695.0,-262774.0,-266459.0,-283540.0,-279467.0
100013,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Amazônia,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,AM,AGROPEC,...,-220554.0,-232664.0,-250233.0,-252002.0,-256416.0,-261695.0,-262774.0,-266459.0,-283540.0,-279467.0
100022,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Amazônia,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,AM,AGROPEC,...,-220554.0,-232664.0,-250233.0,-252002.0,-256416.0,-261695.0,-262774.0,-266459.0,-283540.0,-279467.0

In [ ]:
#Q4
selec = (df['Atividade Econômica'] == 'AGROPEC') & (df['Estado'] == 'PA')
df.loc[selec, 2021].max()

0.0

In [ ]:
colunas_iguais = list(original.loc[:, "Nível 1 - Setor" : "Produto"].columns)
colunas_anos   = list(original.loc[:, 1970:2021].columns)

emissions_per_year = original.melt(id_vars = colunas_iguais, value_vars = colunas_anos, var_name = 'Year', value_name = 'Emission')

In [ ]:
emissions_per_year.groupby("Gás")

In [ ]:
# Q2.1
emissions_per_year.groupby("Nível 1 - Setor").groups

In [ ]:
# Q2.2
emissions_per_year.groupby("Nível 1 - Setor").get_group("Agropecuária")

In [ ]:
# Q2.3
emissions_per_year[[emissions_per_year['Year'] == 2021]].groupby("Nível 1 - Setor")[['Emission']].mean()

In [ ]:
# Q2.4
emissions_per_year.groupby("Nível 1 - Setor")[['Emission']].sum().sort_values('Emission', ascending=False)

In [ ]:
gas_por_setor = emissions_per_year.groupby(['Gás', 'Nível 1 - Setor'])[['Emission']].sum()
gas_por_setor

In [ ]:
gas_por_setor.xs('CO2 (t)', level = 0)
# equivalente a: gas_por_setor.loc[('CO2 (t)', slice(None)), :]
# Outras maneiras
# gas_por_setor.query("Gás == 'CO2 (t)'")
# gas_por_setor.loc['CO2 (t)']

In [ ]:
gas_por_setor.xs(('CO2 (t)', 'Mudança de Uso da Terra e Floresta'), level = [0,1])

In [ ]:
gas_por_setor.xs('CO2 (t)', level = 0).max() # Mas não retorna o setor, somente o valor máximo da Emissão

In [ ]:
gas_por_setor.xs('CO2 (t)', level = 0).idmax() # Retorna somente o setor que tem a emissão máxima

In [ ]:
# Porém, isso está muito manual. Quero achar os setores economicos que mais emitem gas apra TODO gás
gas_por_setor.groupby(level = 0).idxmax()
# Isso me dá o setor que mais emitiu aquele tipo de gás

In [ ]:
valores_max = gas_por_setor.groupby(level = 0).max()
# Isso me dá a qtde máxima de emissão por gás

In [ ]:
# Para juntar tudo em uma mesma tabela
tabela_sumarizada = gas_por_setor.groupby(level = 0).idxmax()
tabela_sumarizada.insert(1, "Quantidade de Emissão", valores_max) # ìndice da coluna; Nome da Nova Coluna; valores a adicionar

In [ ]:
# Agora queremos saber o contrário, ou seja, o gás que mais emite por setor econômico
# Ao invés de ter que repetir todos os códigos anterioes com o level trocado, basta usar swaplevel:
gas_por_setor.swaplevel(0, 1)

In [ ]:
gas_por_setor.swaplevel(0, 1).groupby(level = 0).idxmax()

In [ ]:
emission_per_year.groupby('Year')[['Emission']].mean().plot(figsize = (10,6)); # Testar tirar o ;

In [ ]:
emission_per_year.groupby('Year')[['Emission']].mean().idxmax()

In [ ]:
emission_per_year.groupby(['Year', 'Gás'])[['Emission']].mean()

In [ ]:
media_emissao_anual = emission_per_year.groupby(['Year', 'Gás'])[['Emission']].mean().reset_index()
media_emissao_anual

In [ ]:
media_emissao_anual = media_emissao_anual.pivot_table(index = 'Year', columns = 'Gás', values = 'Emission') # Transforma cada tipo de gás em uma coluna
media_emissao_anual

In [ ]:
media_emissao_anual.plot(subplots = True, figsize = (10, 40)); # Subplots cria um gráfico para cada coluna

In [ ]:
# Q 4.0.1:
emissao_setores = emissoes_por_ano.pivot_table(values = 'Emissão', index = 'Ano', columns = 'Nível 1 - Setor', aggfunc = 'mean')
emissao_setores

In [ ]:
# Q 4.0.1:
emissao_setores.plot(subplots = True, figsize = (10,10));

In [ ]:
# Q 4.1
estado_setor = emission_per_year.groupby(['Estado', 'Nível 1 - Setor'])[['Emission']].sum()

In [ ]:
# Q 4.2
estado_setor.xs('Energia', level=1)

In [ ]:
# Q 4.3
estado_setor.xs('MG', level=0).idmax()

In [ ]:
# Q 4.4
estado_setor.groupby(level=0).idmax()

In [ ]:
# Q 4.5
estado_setor.groupby(level=1).idmax()

In [ ]:
from google.colab import files
uploades = files.upload()

In [ ]:
populacao = pd.read_excel('POP2022_Municipios.xls', header = 1, skipfooter = 34)
populacao.head()

In [ ]:
populacao.info()

In [ ]:
# Vai dar erro. A ideia é corrigir ele em seguida
populacao['POPULAÇÃO'] = populacao['POPULAÇÃO'].astype(int)

In [ ]:
populacao[populacao["POPULAÇÃO"].str.contains('\(', na=False)] # Sem o (, acharia q estava especificando um Regex entre ()

In [ ]:
populacao = populacao.assign(populacao_sem_parenteses = populacao['POPULAÇÃO'].replace('\(\d{1,2}\)' ,'',regex = True),
                populacao_tratada = lambda x : x.loc[:, 'populalcao_sem_parenteses'].replace('\.', '', regex = True))

In [ ]:
populacao[populacao["POPULAÇÃO"].str.contains('\(', na=False)]

In [ ]:
populacao = populacao.astype({'populacao_tratada':'int64'})

In [ ]:
populacao.grouppby('UF')[['POPULAÇÃO']].sum().reset_index()

In [ ]:
emissao_estados = emissions_per_year[emissions_per_year['Year'] == 2021].groupby('Estado')[['Emission']].sum().reset_index()
emissao_estados

In [ ]:
dados_agrupados = pd.merge(emissao_estados, populacao, left_on = 'Estado', right_on = 'UF')
dados_agrupados

In [ ]:
dados_agrupados.plot(x = 'populacao_tratada', y = 'Emission', kind = 'scatter', figsize = (10,6));

In [ ]:
import plotly.express as px
px.scatter(dataframe= dados_agrupados, x = 'populacao_tratada', y = 'Emission', text = 'Estado', opacity = 0)

In [ ]:
# Vamos achar o emissao per capita
dados_agrupados = dados_agrupados.assign(emissao_per_capita = (dados_agrupados['Emission'] / dados_agrupados['populacao_tratada'])).sort_values('emissao+per_capita', ascending = False)
dados_agrupados

In [ ]:
px.bar(dataframe = dadso_agrupados, x = 'Estado', y = 'emissao_per_capita')

In [ ]:
px.scatter(dataframe= dados_agrupados, x = 'populacao_tratada', y = 'Emission', text = 'Estado', opacity = , size = 'emissao_per_capita')